sudo: required

language:
  - cpp

services:
  - docker

install:
  - docker build -t tschijnmo/libcanon_test .

script:
  - >
    docker run --rm tschijnmo/libcanon_test /bin/sh -c
    "mkdir _build;
    cd _build;
    cmake ..;
    make;
    ctest;
    "

